### ISSUE TITLE
Unable to edit card model during review

### ISSUE THREAD

**Issue by ghost** [Arthur-Milchior/anki-big-addon#1]
**Error:**
Debug info:
Anki 2.1.15 (6661ba8a) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\777545149\aqt\clayout.py", line 120, in reject
    self.mm.save(self.model, templates=True, oldModel = self.originalModel, newTemplatesData = self.newTemplatesData) # new: adding oldModel, newTemplatesData
<class 'AttributeError'>: 'CardLayout' object has no attribute 'originalModel'

**Steps to reproduce**
During review open card-type edit menu

**Comment by Arthur-Milchior** [comment]
Strange. May i have your list of add ons, please?

Le mer. 24 juil. 2019 à 16:33, John Smith <notifications@github.com> a
écrit :

**Comment by ghost** [comment]
Oh. It's night mode again.
The fix you pointed out in https://github.com/Arthur-Milchior/anki-fast-note-type-editor/issues/1 fixes this.

**Comment by Arthur-Milchior** [comment]
I'm editing the readme, in order to warn people about it.
